name: Apply ADIOS Patch to Source Code

on:
  workflow_dispatch:

jobs:
  commit-patch:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Apply Patch and Commit
        run: | 
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          echo "Processing patch..."
          patch --3way --ignore-whitespace --recount < adios_4.19.patch || {
            echo "Error"
            find . -name "*.rej" -exec echo "--- {} ---" \; -exec cat {} \;
            exit 1
          }

          rm adios_4.19.patch

          if [ -z "$(git status --porcelain)" ]; then
            echo "There is no changes for commit."
            exit 0
          fi

          git add .
          git commit -m "block: Add ADIOS I/O scheduler (backport to 4.19)"

          git push

