name: Update CIP Kernel Version
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.MY_PAT }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Reset to Clean State
        run: |
          git reset --hard bde139d2d3d968834c38ae905539a2ab34b2be0e

      - name: Push Updates
        run: |
          # ПУШИМ ТОЛЬКО ЯДРО, НЕ ТРОГАЯ ВОРКФЛОУ
          git push -f origin HEAD:main-a16-sm8250-base
