name: Upstream LTS kernel

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-kernel:
    runs-on: ubuntu-latest

    env:
      NEW_BRANCH: lts-upstream
      LTS_REPO: https://github.com/frstprjkt/kernel-lts.git

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git config
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add LTS repository
        run: |
          git remote add kernel-lts $LTS_REPO
          git fetch kernel-lts --tags

      - name: Create new branch
        run: |
          git checkout -b $NEW_BRANCH

      - name: Generate stable patches
        run: |
          mkdir stable-patches

          git format-patch \
          --output-directory stable-patches \
          kernel-lts/v4.19.326..kernel-lts/v4.19.331

          ls -la stable-patches

      - name: Apply stable patches
        run: |
          git am stable-patches/*.patch || {
            echo "git am failed, trying 3-way apply"

            git am --abort || true

            for patch in stable-patches/*.patch; do
              git apply --3way "$patch"
              git add .
              git commit -m "$(basename "$patch")"
            done
          }

      - name: Check kernel version
        run: |
          grep SUBLEVEL Makefile || true

      - name: Push branch
        run: |
          git push origin $NEW_BRANCH