name: Upstream LTS Kernel

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-kernel:
    runs-on: ubuntu-latest

    env:
      NEW_BRANCH: lts-upstream
      LTS_REPO: https://github.com/frstprjkt/kernel-lts.git

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add LTS repository and fetch tags
        run: |
          git remote add kernel-lts $LTS_REPO
          git fetch kernel-lts --tags

      - name: Create new branch
        run: |
          git checkout -b $NEW_BRANCH

      - name: Generate stable patches
        run: |
          mkdir stable-patches
          # Используем имя тегов без префикса репозитория
          git format-patch \
            --output-directory stable-patches \
            v4.19.326..v4.19.331

          ls -la stable-patches

      - name: Apply stable patches
        run: |
          # Запускаем цикл для поочередной обработки каждого патча
          for patch in stable-patches/*.patch; do
            echo "=== Applying: $(basename "$patch") ==="
            # Передаем конкретный патч $patch с маленькой буквы git
            git apply -3 "$patch" || true
          done

          git status
          git add .

      - name: Check kernel version
        run: |
          grep SUBLEVEL Makefile || true

      - name: Push branch
        run: |
          # Безопасный коммит: делаем коммит только при наличии индексированных изменений
          if ! git diff --cached --quiet; then
            git commit -m "Linux 4.19.331 (LTS upstream)"
          else
            echo "No new changes to commit."
          fi

          git push -u origin $NEW_BRANCH
