name: Build Kernel spes 4.19 BPF ksun-susfs
on:
  workflow_dispatch:
  push:
    branches:
      - main-a16-sm8250-base-ksun-susfs

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Download Proton Clang
        run: |
          mkdir -p ${{ github.workspace }}/proton-clang
          curl -LSs "https://github.com/kdrag0n/proton-clang/archive/refs/heads/master.tar.gz" | tar -xz -C ${{ github.workspace }}/proton-clang --strip-components=1
          echo "${{ github.workspace }}/proton-clang/bin" >> $GITHUB_PATH

      - name: Build Kernel spes 4.19 BPF ksun-susfs
        uses: dabao1955/kernel_build_action@main
        env:
          HOSTCFLAGS: "-fuse-ld=lld"
          HOSTLDFLAGS: "-fuse-ld=lld"
        with:
          kernel-url: https://github.com/muralivijay/kernel_xiaomi_spes/
          kernel-dir: msm-4.19
          kernel-branch: main-a16-sm8250-base-ksun-susfs
          config: vendor/spes-perf_defconfig
          arch: arm64
          aosp-gcc: false
          aosp-clang: false
          ksu-other: true
          ksu-url: https://github.com/KernelSU-Next/KernelSU-Next
          anykernel3: true
          anykernel3-url: https://github.com/muralivijay/AnyKernel3
