name: Build Kernel

on:
  workflow_dispatch:

env:
  DEFCONFIG: spes-perf_defconfig
  ARCH: arm64
  SUBARCH: arm64
  KERNEL_NAME: Wild-Kernel

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Set up Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache curl flex git gnupg gperf lib32readline-dev lib32z1-dev lz4 libncurses5-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python3 libelf-dev lld llvm gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

    - name: Download ZyCLLVM Toolchain
      run: |
        mkdir -p clang
        cd clang
        curl -LO "https://github.com/ZyCromerZ/Clang/releases/download/16.0.6-20260716-release/Clang-16.0.6-20260716.tar.gz"
        tar -xf Clang-16.0.6-20260716.tar.gz
        rm Clang-16.0.6-20260716.tar.gz
        cd ..

    - name: Build Kernel
      run: |
        CLANG_BIN=$(find $(pwd)/clang -type d -name "bin" | head -n 1)
        export PATH="$CLANG_BIN:$PATH"
        export ARCH=${{ env.ARCH }}
        export SUBARCH=${{ env.SUBARCH }}
        export CROSS_COMPILE=aarch64-linux-gnu-
        export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
        
        echo "============================================="
        echo "          STARTING KERNEL BUILD              "
        echo "============================================="
        sed -i 's/local short/return 0/g' scripts/setlocalversion
        
        curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/legacy/kernel/setup.sh" | bash -s legacy
        curl -LSs "https://raw.githubusercontent.com/JackA1ltman/NonGKI_Kernel_Build_2nd/mainline/Patches/syscall_hook_patches.sh" | bash -s mainline
        
        echo "CONFIG_MODULES=y" >> arch/${{ env.ARCH }}/configs/${{ env.DEFCONFIG }}
        echo "CONFIG_KSU=y" >> arch/${{ env.ARCH }}/configs/${{ env.DEFCONFIG }}
        echo "CONFIG_KSU_MANUAL_HOOK=y" >> arch/${{ env.ARCH }}/configs/${{ env.DEFCONFIG }}
        echo "CONFIG_KSU_NEXT=y" >> arch/${{ env.ARCH }}/configs/${{ env.DEFCONFIG }}
        echo "CONFIG_COMPAT_VDSO=n" >> arch/${{ env.ARCH }}/configs/${{ env.DEFCONFIG }}
        
        # Передаем CLANG_TRIPLE, чтобы defconfig собрался под ARM64, а не под x86 сервера
        make O=out ${{ env.DEFCONFIG }} CC=clang CLANG_TRIPLE=aarch64-linux-gnu- LD=ld.lld
        make O=out olddefconfig CC=clang CLANG_TRIPLE=aarch64-linux-gnu- LD=ld.lld
        
        make -j$(nproc --all) O=out \
                      CC=clang \
                      CLANG_TRIPLE=aarch64-linux-gnu- \
                      HOSTCC=clang \
                      LD=ld.lld \
                      AR=llvm-ar \
                      NM=llvm-nm \
                      OBJCOPY=llvm-objcopy \
                      OBJDUMP=llvm-objdump \
                      STRIP=llvm-strip \
                      KCFLAGS="-O2 -pipe" \
                      all
        
        echo "============================================="
        echo "          COLLECTING ALL COMPILED FILES      "
        echo "============================================="
        
        mkdir -p build_artifacts

        find out/arch/${{ env.ARCH }}/boot/ -maxdepth 1 -type f \( -name "Image*" -o -name "*.img" \) -exec cp {} ./build_artifacts/ \;

        if [ -z "$(ls -A build_artifacts)" ]; then
          echo "ERROR: No kernel artifacts found! Build failed."
          exit 1
        fi

    - name: Upload Kernel Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.KERNEL_NAME }}-Artifacts
        path: build_artifacts/*
