name: Cherry-pick Remote Commit (Test Branch)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cherry-pick to test branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git checkout -B chrysalis

          git remote add source https://github.com/xxblebleblexx/android_kernel_xiaomi_gale.git
          git fetch source 044910e14a7fcb54083fe1ab311d2cf8e0617adf

          if ! git cherry-pick -m 1 044910e14a7fcb54083fe1ab311d2cf8e0617adf; then
            git add .
            git -c core.editor=true cherry-pick --continue
          fi

          git push origin chrysalis --force
